### ISSUE TITLE
regarding KelpBins_gtdbtk.tsv file

### ISSUE THREAD

**Issue by shakti83kumar** [songweizhi/BioSAK#2]
Dear Sir,
I am Shakti kumar from India working on metagenomics. 
I want to know details about gtdbtk.tsv format. So that I can convert it qiime2 output to gtdbtk.tsv format. 
Kinldy help me

**Comment by songweizhi** [comment]
Hi,
please see an example here:
https://github.com/songweizhi/MetaCHIP/blob/master/input_file_examples/human_gut_bins_GTDB.tsv
